name: test_burning_bros
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.5.0+1
  equatable: ^2.0.5
  get_it: ^7.7.0
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  flutter_bloc: ^8.1.6
  json_annotation: ^4.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
dev_dependencies:
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  
